#!/bin/sh

source /etc/remote-app-terminal.conf
VAR_SERVER="$1"
VAR_USER="$2"
VAR_REMOTE_APP="$3"
VAR_APP_ICON="$4"

help(){
zenity --info --title="help" \
              --text="Парамерты:
              1: сервер
              2: пользователь
              3: имя RemoteApp
              4: app-icon" \
              --width=250 --height=80
}

res=1
ls -l "/bin/zenity"  > /dev/null 2>&1 && res=0
if [ ${res} -ne 0 ] ; then
   echo "Не установлен пакет zenity"
   exit 1;
fi
ls -l "/bin/xfreerdp"  > /dev/null 2>&1 && res=0
if [ ${res} -ne 0 ] ; then
   zenity --error \
          --text="Не установлен пакет xfreerdp" \
          --no-wrap;
   exit 1;
fi
if [ -z "$VAR_SERVER" ]; then
   zenity --error \
          --text="Не указан сервер!" \
          --no-wrap;
   help;
   exit 1;
fi
if [ -z "$VAR_USER" ]; then
   zenity --error \
          --text="Не указан пользователь!" \
          --no-wrap;
   help;
   exit 1;
fi

if [ -z "$VAR_REMOTE_APP" ]; then
   zenity --error \
          --text="Не указано имя RemoteApp!" \
          --no-wrap;
   help;
   exit 1;
fi

eval SERVER=\$$VAR_SERVER
if [ -z "$SERVER" ]; then
   zenity --error \
          --text="Сервер $VAR_SERVER не найден в конфигурации!" \
          --no-wrap;
   exit 1;
fi
PASSW=$( zenity  --entry --title="Проверка прав доступа" --text="Введите пароль для $VAR_SERVER:" \
           --entry-text="" --hide-text );
if [ -z "$PASSW" ]; then
   zenity --error --text="Пароль не введён"
else
   xfreerdp /u:"$VAR_USER" /p:"$PASSW" /app:"||$VAR_REMOTE_APP" /v:"$SERVER" /bpp:15 /app-icon:"$VAR_APP_ICON"
   ERROR=$?

   if [ $ERROR -eq 1 ]; then
      zenity --error \
             --text="Ошибка: $ERROR, отключено административным инструментом на сервере!" \
             --no-wrap;
      exit 1;
   elif [ $ERROR -eq 2 ]; then
      zenity --error \
             --text="Ошибка: $ERROR, вынужденный выход с помощью административного инструмента на сервере!" \
             --no-wrap;
      exit 1;
   elif [ $ERROR -eq 3 ]; then
      zenity --error \
             --text="Ошибка: $ERROR, истекает предельный таймер простоя сервера!" \
             --no-wrap;
      exit 1;
   elif [ $ERROR -eq 4 ]; then
      zenity --error \
             --text="Ошибка: $ERROR, истек срок действия активного таймера сервера!" \
             --no-wrap;
      exit 1;
   elif [ $ERROR -eq 5 ]; then
      zenity --error \
             --text="Ошибка: $ERROR, сессия была заменена!" \
             --no-wrap;
      exit 1;
   elif [ $ERROR -eq 6 ]; then
      zenity --error \
             --text="Ошибка: $ERROR, на сервере закончилась память!" \
             --no-wrap;
      exit 1;
   elif [ $ERROR -eq 7 ]; then
      zenity --error \
             --text="Ошибка: $ERROR, сервер отклонил соединение!" \
             --no-wrap;
      exit 1;
   elif [ $ERROR -eq 8 ]; then
      zenity --error \
             --text="Ошибка: $ERROR, сервер отказал в соединении по соображениям безопасности!" \
             --no-wrap;
      exit 1;
   elif [ $ERROR -eq 9 ]; then
      zenity --error \
             --text="Ошибка: $ERROR, соединение запрещено из-за недостаточных пользовательских привилегий!" \
             --no-wrap;
      exit 1;
   elif [ $ERROR -eq 10 ]; then
      zenity --error \
             --text="Ошибка: $ERROR, сервер требует новых учетных данных!" \
             --no-wrap;
      exit 1;
  ## 11 пропустил
   elif [ $ERROR -eq 16 ]; then
      zenity --error \
             --text="Ошибка: $ERROR, произошла внутренняя ошибка лицензирования!" \
             --no-wrap;
      exit 1;
   elif [ $ERROR -eq 17 ]; then
      zenity --error \
             --text="Ошибка: $ERROR, отсутствует сервер лицензий!" \
             --no-wrap;
      exit 1;
   elif [ $ERROR -eq 18 ]; then
      zenity --error \
             --text="Ошибка: $ERROR, отсутствует действующая лицензия!" \
             --no-wrap;
      exit 1;
   elif [ $ERROR -eq 19 ]; then
      zenity --error \
             --text="Ошибка: $ERROR, недействительное лицензионное сообщение!" \
             --no-wrap;
      exit 1;
   elif [ $ERROR -eq 20 ]; then
      zenity --error \
             --text="Ошибка: $ERROR, лицензия клиентского доступа, сохраненная клиентом, была изменена!" \
             --no-wrap;
      exit 1;
   elif [ $ERROR -eq 21 ]; then
      zenity --error \
             --text="Ошибка: $ERROR, ошибка лицензии клиента" \
             --no-wrap;
      exit 1;
   elif [ $ERROR -eq 22 ]; then
      zenity --error \
             --text="Ошибка: $ERROR, во время протокола лицензирования произошла ошибка сети!" \
             --no-wrap;
      exit 1;
   elif [ $ERROR -eq 23 ]; then
      zenity --error \
             --text="Ошибка: $ERROR, клиент преждевременно прекратил лицензионный протокол!" \
             --no-wrap;
      exit 1;
   elif [ $ERROR -eq 24 ]; then
      zenity --error \
             --text="Ошибка: $ERROR, лицензионное сообщение было неправильно зашифровано!" \
             --no-wrap;
      exit 1;
   elif [ $ERROR -eq 25 ]; then
      zenity --error \
             --text="Ошибка: $ERROR, лицензия клиентского доступа, хранящаяся у клиента, не может быть обновлена!" \
             --no-wrap;
      exit 1;
   elif [ $ERROR -eq 26 ]; then
      zenity --error \
             --text="Ошибка: $ERROR, сервер не имеет лицензии на прием удаленных подключений!" \
             --no-wrap;
      exit 1;
   elif [ $ERROR -eq 32 ]; then
      zenity --error \
             --text="Ошибка: $ERROR, установлен неверный протокол RDP!" \
             --no-wrap;
      exit 1;
   elif [ $ERROR -eq 128 ]; then
      zenity --error \
             --text="Ошибка: $ERROR, неверные параметры!" \
             --no-wrap;
      exit 1;
   elif [ $ERROR -eq 129 ]; then
      zenity --error \
             --text="Ошибка: $ERROR, клиенту недостаточно памяти!" \
             --no-wrap;
      exit 1;
   elif [ $ERROR -eq 130 ]; then
      zenity --error \
             --text="Ошибка: $ERROR, соединение завершено из-за ошибки протокола!" \
             --no-wrap;
      exit 1;
   elif [ $ERROR -eq 131 ]; then
      zenity --error \
             --text="Ошибка: $ERROR, не удалось подключиться к удаленному хосту!" \
             --no-wrap;
      exit 1;
   elif [ $ERROR -eq 132 ]; then
      zenity --error \
             --text="Ошибка: $ERROR, неверный логин или пароль!" \
             --no-wrap;
      exit 1;
   elif [ $ERROR -gt 0 ]; then
      zenity --error \
             --text="Ошибка: $ERROR!" \
             --no-wrap;
      exit 1;
   fi
fi
